  // Docs: https://dbml.dbdiagram.io/docs

  Table user {
    id integer [primary key]
    name varchar(80)
    nickname varchar(15)
    birthday date
    xp integer
    favorite_sport integer
    created_at timestamp

    indexes {
      (birthday)
      (xp)
    }
  }

  Table user_info {
    user_id integer [primary key]
    email varchar(100)
    phone varchar(30)
    city varchar(50)
    state char(2)
    country char(2)
    address varchar(150)

    indexes {
      (city)
      (state)
      (country)
    }
  }

  Table player_favorite_position {
    user_id integer [primary key]
    sport_id integer [primary key]
    position_id integer
    added_at date
  }

  Table sports {
    id integer [primary key]
    name varchar(30)
  }

  Table sports_positions {
    id integer [primary key]
    sport_id integer
    name varchar(30)

    indexes {
      (sport_id)
    }
  }

  Table games {
    id integer [primary key]
    sport_id integer
    location varchar(100)
    game_time datetime
    best_player_id integer [note: "Nullable"]

    indexes {
      (location)
      (best_player_id)
    }
  }

  Table game_players {
    game_id integer [primary key]
    user_id integer [primary key]
    presence boolean [note: "Did the player attend ?"]
  }


  // USER INFORMATION RELATION
  Ref: user.id - user_info.user_id
  Ref: user.favorite_sport - sports.id
  Ref: game_players.user_id > user.id

  // SPORT POSITIONS RELATION
  Ref: sports.id < sports_positions.sport_id
  Ref: player_favorite_position.user_id > user.id
  Ref: player_favorite_position.sport_id - sports.id
  Ref: player_favorite_position.position_id - sports_positions.id

  // GAMES RELATION
  Ref best_player: games.best_player_id > user.id
  Ref game_sport: games.sport_id > sports.id
  Ref: games.id < game_players.game_id