// Docs: https://dbml.dbdiagram.io/docs

Table user {
  id integer [primary key]
  name varchar(80)
  nickname varchar(15)
  birthday date
  xp integer
  created_at timestamp
}

Table user_info {
  user_id integer [primary key]
  email varchar(100)
  phone integer(20)
  city varchar(50)
  state char(2)
  country char(2)
  address varchar(150)
}

Table player_info {
  user_id integer [primary key]
  favorite_sport integer
  // TODO: Create a reference on the favorite position for a sport -> it can be one position to multiple sports
}

Table sports {
  id integer [primary key]
  name varchar(30)
  position varchar
}

Table sports_positions {
  id integer [primary key]
  sport_id integer
  name varchar(30)
}

Table games {
  id integer [primary key]
  user_id integer
  sport integer
  game_time datetime
}

Table best_game_player {
  game_id integer [primary key]
  user_id integer [primary key]
}


// USER INFORMATION RELATION
Ref: user.id - user_info.user_id
Ref: user.id - player_info.user_id
Ref: user.id < games.user_id

// SPORT POSITIONS RELATION
Ref: sports.id < sports_positions.sport_id

// FAVORITE SPORT ON PLAYER INFO
Ref: player_info.favorite_sport - sports.id

// BEST PLAYER OF THE GAME RELATION
Ref game: best_game_player.game_id - games.id
Ref best_player: best_game_player.user_id - user.id