// Docs: https://dbml.dbdiagram.io/docs

Table user {
  id integer [primary key]
  name varchar(80)
  nickname varchar(15)
  birthday date
  xp integer
  created_at timestamp

  indexes {
    (birthday)
    (xp)
  }
}

Table user_info {
  user_id integer [primary key]
  email varchar(100)
  phone varchar(30)
  city varchar(50)
  state char(2)
  country char(2)
  address varchar(150)

  indexes {
    (city)
    (state)
    (country)
  }
}

Table player_info {
  user_id integer [primary key]
  favorite_sport integer
}

Table player_favorite_position {
  user_id integer [primary key]
  sport_id integer [primary key]
  position_id integer
  added_at timestamp
}

Table sports {
  id integer [primary key]
  name varchar(30)
}

Table sports_positions {
  id integer [primary key]
  sport_id integer
  name varchar(30)

  indexes {
    (sport_id)
  }
}

Table games {
  id integer [primary key]
  user_id integer
  sport_id integer
  game_time datetime

  indexes {
    (user_id)
  }
}

Table best_game_player {
  game_id integer [primary key]
  user_id integer [primary key]
}


// USER INFORMATION RELATION
Ref: user.id - user_info.user_id
Ref: user.id - player_info.user_id
Ref: user.id < games.user_id

// SPORT POSITIONS RELATION
Ref: sports.id < sports_positions.sport_id
Ref: player_favorite_position.user_id < user.id
Ref: player_favorite_position.sport_id - sports.id
Ref: player_favorite_position.position_id - sports_positions.id

// FAVORITE SPORT ON PLAYER INFO
Ref: player_info.favorite_sport - sports.id

// GAMES RELATION
Ref: games.sport_id > sports.id

// BEST PLAYER OF THE GAME RELATION
Ref game: best_game_player.game_id - games.id
Ref best_player: best_game_player.user_id - user.id