import type { Metadata } from "next";
import { Roboto, Inter, Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "./shared/header";
import Footer from "./shared/footer";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GamePulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/favicon.png" type="image/png" /> */}
      </head>
      <body
        className={`${roboto.variable} ${inter.variable} ${notoSans.variable} antialiased bg-gray-200`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
